# Default values for docker-mcp-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas
replicaCount: 1

# Docker image configuration
image:
  repository: kalyanram262/mcp-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Container port
containerPort: 8000

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  # Uncomment for NodePort
  # nodePort: 30080
  # Uncomment for LoadBalancer
  # loadBalancerIP: ""
  # loadBalancerSourceRanges: []
  # - 0.0.0.0/0

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: 
      paths:
        - path: /(.*)
          pathType: Prefix
  tls: []
  #  - secretName: docker-mcp-tls
  #    hosts:
  #      - docker-mcp.local

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity: {}

# Environment variables
env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: DOCKER_HOST
    value: "unix:///var/run/docker.sock"
  - name: MCP_SERVER_HOST
    value: "0.0.0.0"
  - name: MCP_SERVER_PORT
    value: "8000"

# Volume mounts for Docker socket in Minikube
volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket

volumeMounts:
  - name: docker-sock
    mountPath: /var/run/docker.sock
    # Required for Minikube to access host's Docker socket

# Security context
securityContext:
  runAsUser: 0  # root user for Docker socket access
  runAsGroup: 0
  fsGroup: 0

# Pod security context
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Pod annotations
podAnnotations: {}

# Service account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Additional environment variables from secrets or configmaps
envFrom: []
# - secretRef:
#     name: my-secret
# - configMapRef:
#     name: my-configmap
